# PyInstaller build for Novena Sync:  cd sync && pyinstaller novena-sync.spec
# Windows: dist/Novena Sync/Novena Sync.exe   macOS: dist/Novena Sync.app
# The GitHub Actions workflow (.github/workflows/sync-app.yml) builds both from the tagged source.
import sys
from pathlib import Path

datas = [("assets/window.png", "assets")]
if Path("NOTICES.txt").exists():  # third-party licenses, generated by the workflow
    datas.append(("NOTICES.txt", "."))

a = Analysis(
    ["run.py"],
    pathex=["."],
    datas=datas,
    hiddenimports=["keyring.backends.Windows", "keyring.backends.macOS", "keyring.backends.SecretService"],
    excludes=["UnityPy", "pymongo", "rsa", "Crypto"],  # ArkPRTS extras Novena Sync doesn't use
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name="Novena Sync",
    console=False,
    icon="assets/novena.ico" if sys.platform == "win32" else "assets/novena.icns",
)
coll = COLLECT(exe, a.binaries, a.datas, name="Novena Sync")
if sys.platform == "darwin":
    app = BUNDLE(coll, name="Novena Sync.app", icon="assets/novena.icns", bundle_identifier="io.github.novena-arknights.sync")
